### ISSUE TITLE
social_user의 classDecoration은 none일 수 있습니다.

### ISSUE THREAD

**Issue by Leeone7200** [solvedac/api.rs#32]
option<ClassDecoration> 이 아닌 ClassDecoration으로 되어 있습니다

**Comment by RanolP** [comment]
1. "none"이 아니라 null일 수 있다는 말씀이신지요? 만약 그러한 경우 해당하는 반례를 [solvedac/unofficial-documentation](https://github.com/solvedac/unofficial-documentation)에 이슈로 제보해주시면 감사하겠습니다. 본 저장소는 응답을 바탕으로 solved.ac 스펙을 추론하기 때문에 null 값이 반환되는 사례가 발견된 경우 그때그때 수정하고 있습니다.
2. "none"이 ClassDecoration::None으로 인코딩되는 것은 정상입니다.

**Comment by RanolP** [comment]
추가적인 활동이 없어 본 이슈를 닫겠습니다. 만약 추가 논의 사항이 있다면 본 이슈를 다시 열어주십시오.
